version: '3.8'

services:
  db:
    image: postgres:15
    container_name: biocore_db
    restart: always
    environment:
      POSTGRES_USER: biocore
      POSTGRES_PASSWORD: biocore123
      POSTGRES_DB: biocore_db
    ports:
      - "5432:5432"
    volumes:
      - biocore_data:/var/lib/postgresql/data

volumes:
  biocore_data: